name: Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Update data
        run: bash update.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            final.zip
